### ISSUE TITLE
Problem loading alabaster-color-theme.json

### ISSUE THREAD

**Issue by bernik** [tonsky/vscode-theme-alabaster#1]
After install and restart, select theme Alabaster
"Problem loading theme: Unable to load $HOME/.vscode/extensions/tonsky.theme-alabaster-0.1.1/theme/alabaster-color-theme.json"

OS: Ubuntu 14.04
VSCode: 1.9.0

**Comment by tonsky** [comment]
Strange. `find $HOME/.vscode/extensions/tonsky.theme-alabaster-0.1.1/` please?

**Comment by bernik** [comment]
```
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/theme
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/theme/alabaster-color-theme.json
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/LICENSE.txt
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/screenshot.png
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/playground.clj
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/icon.png
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/package.json
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/.vsixmanifest
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/CHANGELOG.md
/home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/README.md
```

**Comment by bernik** [comment]
ls -al /home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/theme/alabaster-color-theme.json                                                                                                                  19:51:46 
-rw-r--r-- 1 bernik bernik 2452 Apr 27 19:01 /home/bernik/.vscode/extensions/tonsky.theme-alabaster-0.1.1/theme/alabaster-color-theme.json

**Comment by bernik** [comment]
Upgraded vscode to 1.11.2. This is solve the problem. sorry for disturbing.

**Comment by tonsky** [comment]
Cool, thanks! Maybe something has changed in extensions format since then
