### ISSUE TITLE
[Color] More visible editor.selectionHighlightBackground

### ISSUE THREAD

**Issue by Lisoph** [tonsky/vscode-theme-alabaster#11]
I love this color theme, but one issue I have is that the `editor.selectionHighlightBackground` color is a bit too mute.

I customized the color to `#ffdda8`, which I find to be way more useful, since occurences are way more visible. It looks like this:
![2018-01-29 11_07_37-tmp074915634 cln - visual studio code](https://user-images.githubusercontent.com/3426722/35504959-d4768610-04e4-11e8-9848-cba3c92b7edf.png)

I'd like this color to be the default, but only if enough people agree, since this is really just subjective.

**Comment by tonsky** [comment]
I like it being mute, otherwise it’s too much action happening as I move my cursor around and it’s distracting. But if others like it too maybe I’ll give it a chance

**Comment by Lisoph** [comment]
I'm closing this because customizing the color is perfectly fine and the color value is purely subjective anyway.
