### ISSUE TITLE
Opening single file results in different status bar color

### ISSUE THREAD

**Issue by wonderfulll** [tonsky/vscode-theme-alabaster#13]
Hi,
Is it intentionally left that if I open only one file (`▶ code test.txt`) the status bar becomes purple?
![selection_127](https://user-images.githubusercontent.com/445242/37325999-c6c426c8-2698-11e8-8d3e-7a8ac4f66ba7.png)
Theme definition:
```json
"statusBar.noFolderBackground": "#7A3E9D",
"statusBar.noFolderForeground": "#fff",
```

Proposition as before make it the same color as opening folder:
![selection_128](https://user-images.githubusercontent.com/445242/37326069-1d5b99da-2699-11e8-8f6a-035a80e0b3c3.png)

Code to fix it:
```json
"statusBar.noFolderBackground" : "#DADADA",
"statusBar.noFolderForeground" : "#6C6C6C",
```

**Comment by tonsky** [comment]
Yes, that’s what VS Code does by default. I don’t have an opinion here, so I just left things untouched. Feel free to add it to your own config if it bothers you
