### ISSUE TITLE
HTML Canvas "moveTo" function isn't coloured like other functions

### ISSUE THREAD

**Issue by kristianpedersen** [tonsky/vscode-theme-alabaster#14]
The moveTo function seems like it's not coloured correctly. I'm using 0.2.6 of your theme. Everything else looks great.

![moveto](https://user-images.githubusercontent.com/5204369/42125281-0e984462-7c74-11e8-8484-3454aa6c6bf5.png)

**Comment by tonsky** [comment]
I think it's language plugin that has some built-in list of words it can
highlight and the rest just stays black. Try with other themes, I bet
you'll get the same behaviour

**Comment by kristianpedersen** [comment]
Seems like it's VS Code's default highlighting that does it.

Solution: 
Install "Babel JavaScript" (VS Code extension). Now everything looks correct.
