### ISSUE TITLE
Black alabaster

### ISSUE THREAD

**Issue by yuriykashin** [tonsky/vscode-theme-alabaster#15]
Nice theme. I like its minimal highlight style, and it became my default theme wherever I go.
But what about dark version?

**Comment by tonsky** [comment]
maybe one day

**Comment by lomeat** [comment]
I am still waiting. At the night time choose Default Dark Theme, because in the dark very hard work with light white theme. Please reliase not in next year.

**Comment by apust** [comment]
Until @tonsky makes his dark version, I'm using my own; if you're not into manual color editing, you can give it a try on [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=apust.rubber-theme) or [GitHub](https://github.com/apust/vscode-rubber-theme).

**Comment by ianrohde** [comment]
@tonsky, would you be open to reviewing a forked dark version? I'd like to help push something official forward if I can.

**Comment by tonsky** [comment]
@ianrohde you can publish your own, inspired by alabaster. I’ll be happy to link to it

**Comment by mullakhmetov** [comment]
[Here's](https://github.com/mullakhmetov/vscode-theme-shale) my attempt to make the dark version. It's combination of Alabaster minimal highlighting and Nord color scheme. Open to suggestions.

**Comment by apust** [comment]
@mullakhmetov Looks great! The only suggestion: use a brighter color for comments. Red color for comments in Alabaster is a really useful feature from my experience.

**Comment by lomeat** [comment]
@apust You can fork and make your colors. Every field has good description in vs code. So for comments it will be simple

**Comment by mullakhmetov** [comment]
@apust #b48ead is not bright enough for your taste? Comments were grayish in previous version, but now I've fixed it.

**Comment by gargakshit** [comment]
I tried to copy the colors to the original dark version.

Repo: https://github.com/gargakshit/vscode-theme-alabaster-dark
Marketplace Link: https://marketplace.visualstudio.com/items?itemName=gargakshit.theme-alabaster-dark

**Comment by tonsky** [comment]
@gargakshit that looks great! Can you make a PR that adds this to the README?

**Comment by gargakshit** [comment]
> @gargakshit that looks great! Can you make a PR that adds this to the README?

Done at #27
