### ISSUE TITLE
Releases Working As Expected?

### ISSUE THREAD

**Issue by ianrohde** [tonsky/vscode-theme-alabaster#25]
The latest version of Alabaster I see available is `0.2.7`. I've tried uninstalling and reinstalling, but not seeing `0.2.9` 🤔

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1634505/124863532-11060000-df6c-11eb-86c2-9ef54a6488e7.png">

**Comment by tonsky** [comment]
Ah, I forgot to press the button, sorry. Too used to Sublime, where creating a tag is enough. Should be fixed now
