### ISSUE TITLE
Open VSX Registry

### ISSUE THREAD

**Issue by polemius** [tonsky/vscode-theme-alabaster#26]
First of all thank you for the theme. It looks very great 😍

From time to time I am using Onivim 2. Onivim2 supports vscode extensions but it should be uploaded to [Open VSX Registry](https://open-vsx.org/).

From the Onivim 2 [documentation](https://onivim.github.io/docs/configuration/extensions):

> The VSCode marketplace is proprietary - so Onivim uses the Open VSX marketplace: an open, vendor-neutral repository of VSCode extensions. 

Could you please publish your theme to Open VSX Registry?

**Comment by tonsky** [comment]
I’ll try https://github.com/open-vsx/publish-extensions/pull/391

**Comment by polemius** [comment]
@tonsky Thanks!
