### ISSUE TITLE
Workbench colors, not same with screenshot. Clojure syntax, correct.

### ISSUE THREAD

**Issue by kinahwatts** [tonsky/vscode-theme-alabaster#3]
Hi, I like the motivation for this theme and I think it's great. But I'm having some issues and I'd love some help. After installing and activating the theme:

1. The workbench colors is not purple-ish, rather it is very blue. (Activity bar is dark, Status bar is blue)
2. Syntax colors for `.clj` files is correct except for the background which is white (not purple-ish).
3. Other file (e.g. `.js`) highlights are only red (comments), green (strings), and black all the way.

Here is the screenshot:

![2017-05-12](https://cloud.githubusercontent.com/assets/7811773/26001995/c28d95bc-3760-11e7-9e07-8d6950d9563e.png)

**NOTE:** I tried to generate custom color with the Alabaster theme activated, and the resulting `custom-color-theme.json` file have an empty `"colors: {}"`. I tried generating another theme (Quiet Light+) that uses `.json` file and the resulting `custom-color-theme.json` is the same with the one in the repo.

VS Code: v1.12.1
OS: Windows 10

**Comment by tonsky** [comment]
I updated the screenshot, should be in line with the actual look now
