### ISSUE TITLE
background color highlighting

### ISSUE THREAD

**Issue by MaxBittker** [tonsky/vscode-theme-alabaster#5]
vscode currently doesn't support background color highlighting via their theme api. Theoretically this will change, and this issue is to track the progress / feasibility of this theme looking the same as 
alabaster-lighttable / flatwhite-syntax. 

Feel free to close if you don't feel that this is important to your goals for the theme.

**Comment by tonsky** [comment]
Thanks. Let me know if you learn first when they add this feature in the future
