### ISSUE TITLE
Integrated terminal support

### ISSUE THREAD

**Issue by ebsen** [tonsky/vscode-theme-alabaster#6]
I would love to see colors for Code's integrated terminal at some point.

**Comment by tonsky** [comment]
Well, terminal renders its own colors, doesn’t it?

**Comment by ebsen** [comment]
I'm honestly not sure exactly but I know some themes define their own. 

As an example, Mattia Astorino's Material theme [defines terminal colors](https://github.com/equinusocio/vsc-material-theme/blob/master/themes/Material-Theme-Default.json) in a top-level `colors` key:

```
"terminal.ansiWhite": "#ffffff",
"terminal.ansiBlack": "#546E7A",
"terminal.ansiBlue": "#82AAFF",
"terminal.ansiCyan": "#89DDFF",
"terminal.ansiGreen": "#C3E88D",
"terminal.ansiMagenta": "#C792EA",
"terminal.ansiRed": "#FF5370",
"terminal.ansiYellow": "#FFCB6B",
"terminal.ansiBrightWhite": "#ffffff",
"terminal.ansiBrightBlack": "#546E7A",
"terminal.ansiBrightBlue": "#82AAFF",
"terminal.ansiBrightCyan": "#89DDFF",
"terminal.ansiBrightGreen": "#C3E88D",
"terminal.ansiBrightMagenta": "#C792EA",
"terminal.ansiBrightRed": "#FF5370",
"terminal.ansiBrightYellow": "#FFCB6B",
```

**Comment by tonsky** [comment]
Done. Pull v. 0.2.2

**Comment by tonsky** [comment]
And thanks for the suggestion!

**Comment by ebsen** [comment]
Thank you for incorporating it! It looks much better.
