### ISSUE TITLE
Change status bar color to something not so bright

### ISSUE THREAD

**Issue by wonderfulll** [tonsky/vscode-theme-alabaster#8]
Hi, maybe it would be a good idea to change status bar background color from default blue to something more neutral like: 
```
    "workbench.colorCustomizations": {
        "statusBar.background" : "#DADADA",
        "statusBar.foreground": "#6C6C6C"
    }
```

before:
![selection_081](https://user-images.githubusercontent.com/445242/33470876-3bdf43a0-d673-11e7-902b-9ebd446c6926.png)

after:
![selection_080](https://user-images.githubusercontent.com/445242/33470851-20d299fe-d673-11e7-9587-7495fcb593e1.png)

**Comment by tonsky** [comment]
Pushed v0.2.3
